<?php

return array(
    "client_modules" => array(
        'lip-json2',
        'lip-excanvas',
        'lip-canvas-to-blob',
        'lip-load-image',
        'lip-jquery-2.1.1',
        'lip-bootstrap-3.3.5',
        'lip-font-awesome',
        'lip-cf',
        'lip-jquery-ui-1.12.1.custom',
        'lip-jquery.dialog2',
        'lip-slimscroll',
        'lip-fileupload',
        'lip-wysihtml5',
        'lip-notify',
        'lip-bootbox',
        'lip-form',
        'lip-controls',
        'lip-event',
        'lip-effects',
        'lip-validation',
        'lip-easing',
        'lip-chosen',
        'lip-uniform',
        'lip-select2',
        'lip-modernizr',
    ),
    "js" => array(
        "capp.js",
        "cresenity.js",
    ),
    "css" => array(
        "cresenity.colors.css",
        "cresenity.main.css",
        "cresenity.responsive.css",
        "cresenity.pos.css",
        "cresenity.retail.css",
        "cresenity.widget.css",
        "cresenity.table.css",
        "cresenity.css",
        "lip.css",
    ),
);
